/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Alexis BRENON <brenon.alexis@gmail.com>
 */
public class deliverablePanel extends javax.swing.JPanel {

    /**
     * Creates new form deliverablePanel
     */
    public deliverablePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        decorationPanel2 = new views.decorationPanel();
        jLabel1 = new javax.swing.JLabel();
        deliverablesCombo = new javax.swing.JComboBox();
        contentPanel = new javax.swing.JPanel();
        beveragePanel1 = new views.beveragePanel();

        jLabel1.setText("Livrables");

        deliverablesCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Boissons", "Décorations" }));
        deliverablesCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliverablesComboActionPerformed(evt);
            }
        });

        contentPanel.setLayout(new java.awt.BorderLayout());
        contentPanel.add(beveragePanel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deliverablesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
            .addComponent(contentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliverablesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deliverablesComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliverablesComboActionPerformed
        this.contentPanel.removeAll();
        switch (deliverablesCombo.getSelectedIndex()) {
            case 0:
                this.contentPanel.add(beveragePanel1);
                break;
            case 1:
                this.contentPanel.add(decorationPanel2);
                break;
            default:
                throw new RuntimeException("Unable to display this unknown Panel");
        }
        this.contentPanel.revalidate();
        this.contentPanel.repaint();

    }//GEN-LAST:event_deliverablesComboActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private views.beveragePanel beveragePanel1;
    private javax.swing.JPanel contentPanel;
    private views.decorationPanel decorationPanel2;
    private javax.swing.JComboBox deliverablesCombo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
